services:
  app:
    image: stonesea/ilock-http-service:latest
    container_name: ilock_http_service
    restart: always
    ports:
      - "20033:20033"
    environment:
      - SERVER_PORT=20033
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1090119your
      - DB_NAME=ilock_db
      - DB_TIMEZONE=Asia/Shanghai
      - DB_MIGRATION_MODE=alter
      - TZ=Asia/Shanghai
      - JWT_SECRET_KEY=ilock-secret-key-change-in-production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - ALIYUN_ACCESS_KEY_ID=67613a6a74064cad9859c8f794980cae
      - ALIYUN_ACCESS_KEY_SECRET=your_aliyun_key_secret
      - ALIYUN_RTC_APP_ID=md3fh5x4
      - ALIYUN_RTC_REGION=cn-hangzhou
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    depends_on:
      - db
      - redis
    networks:
      - ilock_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20033/api/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: mysql:8.0
    container_name: ilock_mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1090119your
      - MYSQL_DATABASE=ilock_db
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ilock_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0-alpine
    container_name: ilock_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - ilock_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ilock_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 