services:
  app:
    build: .
    container_name: ilock_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Shanghai
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1090119your
      - DB_NAME=ilock_db
      - DB_TIMEZONE=Asia/Shanghai
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - WEATHER_API_KEY=your_weather_api_key
      - ALIYUN_ACCESS_KEY_ID=67613a6a74064cad9859c8f794980cae
      - ALIYUN_ACCESS_KEY_SECRET=your_aliyun_key_secret
      - ALIYUN_RTC_APP_ID=md3fh5x4
      - ALIYUN_RTC_REGION=cn-hangzhou
      - JWT_SECRET_KEY=your_jwt_secret_key_123456789
      - MOJI_WEATHER_ID=1033800574024974
      - MOJI_WEATHER_KEY=DIlHX7u7v5jFONwJMSMEnPcnOAHYSZ
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mysql
      - redis
    networks:
      - ilock_network

  mysql:
    image: mysql:8.0
    container_name: ilock_mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=1090119your
      - MYSQL_DATABASE=ilock_db
      - MYSQL_USER=ilock_user
      - MYSQL_PASSWORD=1090119your
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ilock_network

  redis:
    image: redis:7.4.1
    container_name: ilock_redis
    restart: always
    ports:
      - "6380:6379"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - redis_data:/data
    networks:
      - ilock_network

networks:
  ilock_network:
    driver: bridge

volumes:
  mysql_data:
    name: ilock_mysql_data
  redis_data:
    name: ilock_redis_data 