version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/ilock-service:latest
    container_name: ilock_app
    restart: always
    ports:
      - "20033:20033"
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Shanghai
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1090119your
      - DB_NAME=ilock_db
      - DB_TIMEZONE=Asia/Shanghai
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - ALIYUN_ACCESS_KEY_ID=67613a6a74064cad9859c8f794980cae
      - ALIYUN_ACCESS_KEY_SECRET=your_aliyun_key_secret
      - ALIYUN_RTC_APP_ID=md3fh5x4
      - ALIYUN_RTC_REGION=cn-hangzhou
      - JWT_SECRET_KEY=your_jwt_secret_key_123456789
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      - ilock_network

  db:
    image: mysql:8.0
    container_name: ilock_mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=ilock_user
      - MYSQL_PASSWORD=1090119your
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ilock_network

  redis:
    image: redis:7.0-alpine
    container_name: ilock_redis
    restart: always
    ports:
      - "6380:6379"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - redis_data:/data
    networks:
      - ilock_network

networks:
  ilock_network:
    driver: bridge

volumes:
  mysql_data:
    name: ilock_mysql_data
  redis_data:
    name: ilock_redis_data 