name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21'
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/ilock-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Verify Go modules
      run: |
        go mod verify
        go mod tidy

    - name: Build
      run: |
        export GOPROXY=https://goproxy.cn,direct
        go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Copy deployment files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "docker-compose.yml,.env"
        target: "/root/ilock"
        strip_components: 0

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /root/ilock
          
          # 确保目录存在
          mkdir -p /root/ilock/logs
          
          # 检查docker-compose.yml是否存在
          if [ ! -f docker-compose.yml ]; then
            echo "Error: docker-compose.yml not found!"
            exit 1
          fi
          
          # 停止现有服务
          docker-compose down || true
          
          # 拉取新镜像
          docker-compose pull
          
          # 启动服务
          docker-compose up -d
          
          # 等待服务启动
          echo "Waiting for service to start..."
          sleep 10
          
          # 健康检查
          for i in {1..30}; do
            if curl -s http://localhost:20033/api/ping > /dev/null; then
              echo "Service is up!"
              exit 0
            fi
            echo "Attempt $i/30: Service not ready yet..."
            
            # 显示容器日志
            echo "Container logs:"
            docker-compose logs --tail=50 app
            
            sleep 2
          done
          
          echo "Service failed to start"
          echo "Full container logs:"
          docker-compose logs
          exit 1 